### ISSUE TITLE
Respect case sensitivity in strings

### ISSUE THREAD

**Issue by s0kil** [linkdata/inifile#1]
@linkdata 

Hey, thanks for sharing this lib!

One little issue I can across is that uppercase chars are parsed and lowercased:

Example, INI File

```
[56A1B3]
en=SM`A`'s `B`chip does not return to the nonce at all
```

The `56A1B3` is parsed as `56a1b3` by the library

**Comment by linkdata** [comment]
Also, it strips leading and trailing whitespace from section and key names.
This is by design. Do you have a usecase where you need case sensitive section names?

**Comment by linkdata** [comment]
No response, so closing.
